drop table if exists `FACE`;

create table `FACE` (
        ID VARCHAR(255) NOT NULL PRIMARY KEY,
        POINT_ZERO VARCHAR(255) NOT NULL,
        POINT_ONE VARCHAR(255) NOT NULL,
        POINT_TWO VARCHAR(255) NOT NULL,
        POINT_THREE VARCHAR(255) NOT NULL,
        POINT_FOUR VARCHAR(255) NOT NULL,
        POINT_FIVE VARCHAR(255) NOT NULL,
        POINT_SIX VARCHAR(255) NOT NULL,
        POINT_SEVEN VARCHAR(255) NOT NULL,
        POINT_EIGHT VARCHAR(255) NOT NULL,
        POINT_NINE VARCHAR(255) NOT NULL,
        POINT_TEN VARCHAR(255) NOT NULL,
        POINT_ELEVEN VARCHAR(255) NOT NULL,
        POINT_TWELVE VARCHAR(255) NOT NULL
);

drop table if exists `TILE`;

create table `TILE` (
        ID VARCHAR(255) NOT NULL PRIMARY KEY,
        DESCRIPTION VARCHAR(255) NOT NULL,
        FACE_A_ID VARCHAR(255) NOT NULL,
        FACE_B_ID VARCHAR(255) NOT NULL,
        FACE_C_ID VARCHAR(255) NOT NULL,
        FACE_D_ID VARCHAR(255) NOT NULL,
        FACE_E_ID VARCHAR(255) NOT NULL,
        FACE_F_ID VARCHAR(255) NOT NULL
);